doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            empty_string_or_null_string: SWP\Bundle\ContentBundle\Doctrine\Types\EmptyStringOrNullStringType
        mapping_types:
            json: string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: false
                metadata_cache_driver:
                    type: pool
                    pool: doctrine.system_cache_pool
                query_cache_driver:
                    type: pool
                    pool: doctrine.system_cache_pool
                result_cache_driver:
                    type: pool
                    pool: doctrine.result_cache_pool
