FROM php:7.3-fpm-alpine

RUN apk update
RUN apk add curl-dev

RUN set -ex \
    && apk --no-cache add \
        postgresql-dev \
        zlib-dev \
        libxml2-dev \
        freetype \
        libpng \
        libjpeg-turbo \
        freetype-dev \
        libpng-dev \
        libjpeg-turbo-dev \
        libintl \
        icu \
        icu-dev \
        git \
        libmemcached-dev \
        autoconf \
        build-base \
        rabbitmq-c-dev \
        libzip-dev \
        zip \
	    libzmq \
        zeromq-dev \
        supervisor \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql \
    && docker-php-ext-install opcache \
    && docker-php-ext-install sockets \
    && pecl install memcached \
    && docker-php-ext-enable memcached \
    && pecl install amqp \
    && docker-php-ext-enable amqp \
    && pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-install exif \
    && docker-php-ext-configure gd \
        --with-png-dir=/usr/include/ \
        --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-configure zip --with-libzip \
    && docker-php-ext-install zip xml gd mbstring curl bcmath
    # && pecl install zmq \
    # && docker-php-ext-enable zmq

RUN curl --insecure https://getcomposer.org/composer.phar -o /usr/bin/composer && chmod +x /usr/bin/composer

# Set timezone
RUN rm -f /etc/localtime
RUN ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime

COPY . /var/www/publisher/
WORKDIR /var/www/publisher/
RUN php /usr/bin/composer install \
 && php /usr/bin/composer dump-autoload \
 && php /usr/bin/composer dump-env dev
 
COPY supervisor.ini /etc/supervisor.d/supervisor.ini

CMD ["supervisord"]
