<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    Sylius\Bundle\ThemeBundle\SyliusThemeBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    FOS\HttpCacheBundle\FOSHttpCacheBundle::class => ['all' => true],
    FOS\RestBundle\FOSRestBundle::class => ['all' => true],
    Knp\Bundle\PaginatorBundle\KnpPaginatorBundle::class => ['all' => true],
    Knp\Bundle\TimeBundle\KnpTimeBundle::class => ['all' => true],
    EmanueleMinotto\TwigCacheBundle\TwigCacheBundle::class => ['all' => true],
    Bazinga\Bundle\HateoasBundle\BazingaHateoasBundle::class => ['all' => true],
    Nelmio\CorsBundle\NelmioCorsBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    Symfony\Cmf\Bundle\RoutingBundle\CmfRoutingBundle::class => ['all' => true],
    JMS\TranslationBundle\JMSTranslationBundle::class => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    Oneup\FlysystemBundle\OneupFlysystemBundle::class => ['all' => true],
    Burgov\Bundle\KeyValueFormBundle\BurgovKeyValueFormBundle::class => ['all' => true],
    Takeit\Bundle\AmpHtmlBundle\TakeitAmpHtmlBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => ['all' => true],
    Gesdinet\JWTRefreshTokenBundle\GesdinetJWTRefreshTokenBundle::class => ['all' => true],
    SWP\Bundle\StorageBundle\SWPStorageBundle::class => ['all' => true],
    SWP\Bundle\MultiTenancyBundle\SWPMultiTenancyBundle::class => ['all' => true],
    SWP\Bundle\TemplatesSystemBundle\SWPTemplatesSystemBundle::class => ['all' => true],
    SWP\Bundle\BridgeBundle\SWPBridgeBundle::class => ['all' => true],
    SWP\Bundle\ContentBundle\SWPContentBundle::class => ['all' => true],
    SWP\Bundle\AnalyticsBundle\SWPAnalyticsBundle::class => ['all' => true],
    SWP\Bundle\RuleBundle\SWPRuleBundle::class => ['all' => true],
    SWP\Bundle\MenuBundle\SWPMenuBundle::class => ['all' => true],
    SWP\Bundle\ContentListBundle\SWPContentListBundle::class => ['all' => true],
    SWP\Bundle\FacebookInstantArticlesBundle\SWPFacebookInstantArticlesBundle::class => ['all' => true],
    SWP\Bundle\UserBundle\SWPUserBundle::class => ['all' => true],
    SWP\Bundle\SettingsBundle\SWPSettingsBundle::class => ['all' => true],
    SWP\Bundle\WebhookBundle\SWPWebhookBundle::class => ['all' => true],
    SWP\Bundle\OutputChannelBundle\SWPOutputChannelBundle::class => ['all' => true],
    SWP\Bundle\PaywallBundle\SWPPaywallBundle::class => ['all' => true],
    SWP\Bundle\SeoBundle\SWPSeoBundle::class => ['all' => true],
    SWP\Bundle\GeoIPBundle\SWPGeoIPBundle::class => ['all' => true],
    SWP\Bundle\RedirectRouteBundle\SWPRedirectRouteBundle::class => ['all' => true],
    SWP\Bundle\CoreBundle\SWPCoreBundle::class => ['all' => true],
    FOS\ElasticaBundle\FOSElasticaBundle::class => ['all' => true],
    SWP\Bundle\ElasticSearchBundle\SWPElasticSearchBundle::class => ['all' => true],
    Gos\Bundle\WebSocketBundle\GosWebSocketBundle::class => ['all' => true],
    Gos\Bundle\PubSubRouterBundle\GosPubSubRouterBundle::class => ['all' => true],
    Sentry\SentryBundle\SentryBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    Nelmio\Alice\Bridge\Symfony\NelmioAliceBundle::class => ['dev' => true, 'test' => true],
    Fidry\AliceDataFixtures\Bridge\Symfony\FidryAliceDataFixturesBundle::class => ['dev' => true, 'test' => true],
    SWP\Bundle\FixturesBundle\SWPFixturesBundle::class => ['dev' => true, 'test' => true],
//    Pixers\DoctrineProfilerBundle\PixersDoctrineProfilerBundle::class => ['dev' => true, 'test' => true],
    Liip\FunctionalTestBundle\LiipFunctionalTestBundle::class => ['test' => true],
    FriendsOfBehat\SymfonyExtension\Bundle\FriendsOfBehatSymfonyExtensionBundle::class => ['test' => true],
    KnpU\OAuth2ClientBundle\KnpUOAuth2ClientBundle::class => ['all' => true],
    SymfonyCasts\Bundle\ResetPassword\SymfonyCastsResetPasswordBundle::class => ['all' => true],
    SymfonyCasts\Bundle\VerifyEmail\SymfonyCastsVerifyEmailBundle::class => ['all' => true],
];
